#
# MOPED Development Environment
#

version: '3.7'
services:
    #
    # Local PostgreSQL database
    #   Note: Attempted using the leanest version (alpine), feel free
    #   to use any other image, as long as the port configuration
    #   and access configuration (user, db, password) are all the same.
    #
    moped-pgsql:
        image: postgres:12-alpine
        volumes:
            - moped-db-vol:/var/lib/postgresql/data
        expose:
            - 5432
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=moped
            - POSTGRES_PASSWORD=moped
            - POSTGRES_DB=moped

    hasura:
        image: hasura/graphql-engine:v1.3.2
        restart: always
        depends_on:
            - moped-pgsql
        expose:
            - 8080
        ports:
            - 8080:8080
        environment:
            - HASURA_GRAPHQL_ENABLE_CONSOLE=false
            - HASURA_GRAPHQL_ENABLE_TELEMETRY=false
            - HASURA_GRAPHQL_DATABASE_URL=postgres://moped:moped@moped-pgsql:5432/moped

volumes:
    moped-db-vol:
        driver: local
